// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
];

const customers = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    name: 'Delba de Oliveira',
    email: 'delba@oliveira.com',
    image_url: '/customers/delba-de-oliveira.png',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    name: 'Lee Robinson',
    email: 'lee@robinson.com',
    image_url: '/customers/lee-robinson.png',
  },
  {
    id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',
    name: 'Hector Simpson',
    email: 'hector@simpson.com',
    image_url: '/customers/hector-simpson.png',
  },
  {
    id: '50ca3e18-62cd-11ee-8c99-0242ac120002',
    name: 'Steven Tey',
    email: 'steven@tey.com',
    image_url: '/customers/steven-tey.png',
  },
  {
    id: '3958dc9e-787f-4377-85e9-fec4b6a6442a',
    name: 'Steph Dietz',
    email: 'steph@dietz.com',
    image_url: '/customers/steph-dietz.png',
  },
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    name: 'Michael Novotny',
    email: 'michael@novotny.com',
    image_url: '/customers/michael-novotny.png',
  },
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    name: 'Evil Rabbit',
    email: 'evil@rabbit.com',
    image_url: '/customers/evil-rabbit.png',
  },
  {
    id: '126eed9c-c90c-4ef6-a4a8-fcf7408d3c66',
    name: 'Emil Kowalski',
    email: 'emil@kowalski.com',
    image_url: '/customers/emil-kowalski.png',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    name: 'Amy Burns',
    email: 'amy@burns.com',
    image_url: '/customers/amy-burns.png',
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    name: 'Balazs Orban',
    email: 'balazs@orban.com',
    image_url: '/customers/balazs-orban.png',
  },
];

const invoices = [
  {
    customer_id: customers[0].id,
    amount: 15795,
    status: 'pending',
    date: '2022-12-06',
  },
  {
    customer_id: customers[1].id,
    amount: 20348,
    status: 'pending',
    date: '2022-11-14',
  },
  {
    customer_id: customers[4].id,
    amount: 3040,
    status: 'paid',
    date: '2022-10-29',
  },
  {
    customer_id: customers[3].id,
    amount: 44800,
    status: 'paid',
    date: '2023-09-10',
  },
  {
    customer_id: customers[5].id,
    amount: 34577,
    status: 'pending',
    date: '2023-08-05',
  },
  {
    customer_id: customers[7].id,
    amount: 54246,
    status: 'pending',
    date: '2023-07-16',
  },
  {
    customer_id: customers[6].id,
    amount: 666,
    status: 'pending',
    date: '2023-06-27',
  },
  {
    customer_id: customers[3].id,
    amount: 32545,
    status: 'paid',
    date: '2023-06-09',
  },
  {
    customer_id: customers[4].id,
    amount: 1250,
    status: 'paid',
    date: '2023-06-17',
  },
  {
    customer_id: customers[5].id,
    amount: 8546,
    status: 'paid',
    date: '2023-06-07',
  },
  {
    customer_id: customers[1].id,
    amount: 500,
    status: 'paid',
    date: '2023-08-19',
  },
  {
    customer_id: customers[5].id,
    amount: 8945,
    status: 'paid',
    date: '2023-06-03',
  },
  {
    customer_id: customers[2].id,
    amount: 8945,
    status: 'paid',
    date: '2023-06-18',
  },
  {
    customer_id: customers[0].id,
    amount: 8945,
    status: 'paid',
    date: '2023-10-04',
  },
  {
    customer_id: customers[2].id,
    amount: 1000,
    status: 'paid',
    date: '2022-06-05',
  },
];

const revenue = [
  { month: 'Jan', revenue: 0 },
  { month: 'Feb', revenue: 0 },
  { month: 'Mar', revenue: 0 },
  { month: 'Apr', revenue: 0 },
  { month: 'May', revenue: 0 },
  { month: 'Jun', revenue: 0 },
  { month: 'Jul', revenue: 0 },
  { month: 'Aug', revenue: 0 },
  { month: 'Sep', revenue: 700 },
  { month: 'Oct', revenue: 1400 },
  { month: 'Nov', revenue: 1100 },
  { month: 'Dec', revenue: 0 },
];



const lessonFields = [
{
  lessonID: 1,
  lesson: 'Stand up straight with your shoulders back.',
  lessonNotes: 'Peterson emphasizes the importance of adopting a posture of confidence and assertiveness. According to Peterson, body language not only influences how others perceive us but also affects our self-perception. Standing tall and maintaining good posture signals strength and resilience, both to the external world and to oneself. This rule encourages individuals to face lifes challenges with courage, embodying a metaphorical readiness to confront adversity. By physically presenting oneself confidently, individuals may find it easier to navigate the complexities of existence and build a foundation for personal growth and success.',
  lessonType: 'Physical Improvement',
  lessonUse: "Social Situations",
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},  
{
  lessonID: 2,
  lesson: 'Treat yourself like someone you are responsible for helping.',
  lessonNotes: 'Peterson advocates for self-compassion, encouraging individuals to care for themselves as they would for others. Recognizing ones worth and addressing personal needs fosters a positive, nurturing mindset.',
  lessonType: 'Self-Compassion',
  lessonUse: 'Personal Development',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 3,
  lesson: 'Make friends with people who want the best for you.',
  lessonNotes: 'Building supportive connections is crucial. Peterson advises seeking relationships where mutual growth and well-being are prioritized, promoting a positive and constructive social environment.',
  lessonType: 'Social Relationships',
  lessonUse: 'Friendship',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 4,
  lesson: 'Compare yourself to who you were yesterday, not to who someone else is today.',
  lessonNotes: 'Focusing on personal progress rather than external benchmarks cultivates self-improvement. Peterson encourages individuals to set realistic goals and measure success relative to their unique journeys.',
  lessonType: 'Self-Reflection',
  lessonUse: 'Goal Setting',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 5,
  lesson: 'Do not let your children do anything that makes you dislike them.',
  lessonNotes: 'Parenting advice from Peterson emphasizes the importance of instilling discipline and values in children. Building a positive relationship requires setting boundaries and guiding with love.',
  lessonType: 'Parenting',
  lessonUse: 'Child Development',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 6,
  lesson:'Set your house in perfect order before you criticize the world.',
  lessonNotes: 'Before addressing external issues, Peterson suggests addressing personal challenges. Organizing ones life creates a stable foundation for making meaningful contributions to the broader community.',
  lessonType: 'Personal Development',
  lessonUse: 'Self-Improvement',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 7,
  lesson: 'Pursue what is meaningful (not what is expedient).',
  lessonNotes: 'Choosing meaningful pursuits over quick gains contributes to a fulfilling life. Peterson encourages aligning actions with long-term values, fostering a sense of purpose.',
  lessonType: 'Life Purpose',
  lessonUse: 'Decision-Making',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 8,
  lesson: 'Tell the truth, or at least dont lie.',
  lessonNotes: 'Honesty, according to Peterson, is fundamental for personal integrity. Being truthful, even in challenging situations, builds trust and authentic connections.',
  lessonType: 'Integrity',
  lessonUse: 'Communication',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 9,
  lesson: 'Assume that the person you are listening to might know something you dont.',
  lessonNotes: 'Encouraging open-mindedness, Peterson advises active listening. Being receptive to others perspectives fosters continuous learning and understanding.',
  lessonType: 'Communication',
  lessonUse: 'Empathy',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 10,
  lesson: 'Be precise in your speech.',
  lessonNotes: 'Clarity in communication is essential for effective expression. Peterson emphasizes the importance of articulating thoughts accurately to avoid misunderstandings.',
  lessonType: 'Communication',
  lessonUse: 'Effective Expression',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 11,
  lesson: 'Do not bother children when they are skateboarding.',
  lessonNotes: 'Acknowledging the importance of risk-taking and exploration in youth, Peterson suggests allowing children to engage in activities that promote independence and resilience.',
  lessonType: 'Parenting',
  lessonUse: 'Child Development',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
},
{
  lessonID: 12,
  lesson: 'Pet a cat when you encounter one on the street.',
  lessonNotes: 'Encouraging small, positive actions in daily life, Peterson uses this rule metaphorically to highlight the significance of finding joy in simple moments.',
  lessonType: 'Life Satisfaction',
  lessonUse: 'Mindfulness',
  lessonSource: '12 Rules for Life: An Antidote to Chaos',
  lessonAuthor: "Jordon Peterson",
  lessonDate: 28/11/2023,
}
];

module.exports = {
  users,
  customers,
  invoices,
  revenue,
  lessonFields,
};